blank_issues_enabled: false
contact_links:
  - name: "Help and Support"
    url: https://github.com/Stage-Whisper/Stage-Whisper/discussions/categories/questions-and-answers
    about: "Need help getting something to work, but you're not sure it's worth of submitting an issue? Ask here."
  - name: "New Feature Ideas"
    url: https://github.com/Stage-Whisper/Stage-Whisper/discussions/categories/new-ideas
    about: "Have a great idea for a new feature or behavior? Tell us and the community about it."
  - name: "Chat on Discord"
    url: https://discord.gg/Kj8GYSxWGd
    about: 'You can ask for help or chat with other users or developers on the Stage Whisper Discord server.'