name: CI - Vite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    # Set the working directory to the front end for all steps in the job
    defaults:
      run:
        working-directory: electron # Set the working directory to the front end for all steps in the job

    steps:
      # Checkout the repository
      - name: Check out Git repository
        uses: actions/checkout@v3

        # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: "npm"
          cache-dependency-path: electron/package-lock.json

      # Install dependencies
      - run: npm ci
      - run: npm build:vite

      # Run Linters
      - run: npm run lint

      # Tests
      # - run: npm test
